<?php
 
	$bundled_product = new Mage_Catalog_Model_Product();		
	$bundled_product->load(21);
 
 
	$selectionCollection = $bundled_product->getTypeInstance(true)->getSelectionsCollection(
		$bundled_product->getTypeInstance(true)->getOptionsIds($bundled_product), $bundled_product
	);
 
	$bundled_items = array();
	foreach($selectionCollection as $option) 
	{
		var_dump($option);
		echo '<br/><br/><br/>';
		$bundled_items[] = $option->product_id;
	}
 
	print_r($bundled_items);
	echo '<br/><br/><br/>';
	echo json_encode($bundled_items);
 
?>